[package]
name = "duniter-documents"
version = "0.4.1"
authors = ["nanocryk <nanocryk@duniter.org>", "elois <elois@ifee.fr>"]
description = "Implements the Duniter Protocol"
repository = "https://git.duniter.org/nodes/rust/duniter-rs"
readme = "README.md"
keywords = ["duniter", "blockchain", "cryptocurrency", "document"]
license = "AGPL-3.0"

[lib]
path = "lib.rs"

[dependencies]
rust-crypto = "0.2.36"
linked-hash-map = "0.5.0"
base58 = "0.1.0"
base64 = "0.8.0"
lazy_static = "1.0.0"
regex = "0.2"
duniter-crypto = { path = "../crypto" }

[features]
# Treat warnings as a build error.
strict = []